/**
 * Centralized Error Codes
 * All application error codes in one place for consistency
 */

export const ERROR_CODES = {
  // Auth
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  MISSING_CREDENTIALS: 'MISSING_CREDENTIALS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
  MISSING_REFRESH_TOKEN: 'MISSING_REFRESH_TOKEN',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',

  // Products
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_UNAVAILABLE: 'PRODUCT_UNAVAILABLE',
  VARIANT_NOT_FOUND: 'VARIANT_NOT_FOUND',
  VARIANT_REQUIRED: 'VARIANT_REQUIRED',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  EXCEEDS_STOCK: 'EXCEEDS_STOCK',

  // Cart
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  CART_EMPTY: 'CART_EMPTY',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  INVALID_QUANTITY: 'INVALID_QUANTITY',

  // Wishlist
  ALREADY_IN_WISHLIST: 'ALREADY_IN_WISHLIST',
  WISHLIST_NOT_FOUND: 'WISHLIST_NOT_FOUND',
  NOT_IN_WISHLIST: 'NOT_IN_WISHLIST',

  // Orders
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  CANNOT_CANCEL: 'CANNOT_CANCEL',
  CANNOT_RETURN: 'CANNOT_RETURN',
  RETURN_WINDOW_EXPIRED: 'RETURN_WINDOW_EXPIRED',

  // Payments
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  MISSING_SIGNATURE: 'MISSING_SIGNATURE',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',

  // Coupons
  INVALID_COUPON: 'INVALID_COUPON',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_LIMIT_REACHED: 'COUPON_LIMIT_REACHED',
  COUPON_NOT_FOUND: 'COUPON_NOT_FOUND',
  MIN_ORDER_NOT_MET: 'MIN_ORDER_NOT_MET',

  // Reviews
  ALREADY_REVIEWED: 'ALREADY_REVIEWED',
  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
  MISSING_PRODUCT_ID: 'MISSING_PRODUCT_ID',

  // Collections / Categories
  COLLECTION_NOT_FOUND: 'COLLECTION_NOT_FOUND',
  DROP_NOT_LIVE: 'DROP_NOT_LIVE',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',

  // Users / Addresses
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',

  // Generic (auto-set by error middleware)
  INVALID_ID: 'INVALID_ID',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE_KEY: 'DUPLICATE_KEY',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
